### ISSUE TITLE
Set for Continuous Integration

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#258]
We should look into setting up a Continuous Integration system with [travis-ci](https://travis-ci.org). Connect the github repo and install a configuration file

  + Trigger on a commit to `master`
  + Run unit tests
  + Run code coverage
  + Successful deploy to -q [Racksapce deploy guide](https://docs.travis-ci.com/user/deployment/cloudfiles/)
  + Report results

<details>
 <summary>Travis YML file</summary>

```
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/

# Run tests against all these PHP versions
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

# Uncomment out to submit code coverage report to scrutinizer
#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
```

</details>
